apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.resourceName }}-web-server-configmap
data:
  WEB_SERVER_PORT: {{ .Values.webServer.conf.port | quote }}
  SPRING_ACTIVE_PROFILES: {{ .Values.webServer.conf.profiles | quote }}
  JDBC_DRIVER_NAME: {{ .Values.datasource.conf.driverClassName | quote }}
  JDBC_URL: {{ .Values.datasource.conf.url | quote }}
  JDBC_PASSWORD: {{ .Values.datasource.conf.password | quote }}
  JDBC_USER: {{ .Values.datasource.conf.username | quote }}
  RPC_USER: {{ .Values.corda.conf.rpc.username | quote }}
  RPC_PASSWORD: {{ .Values.corda.conf.rpc.password | quote }}
  RPC_HOST: {{ .Values.corda.conf.rpc.host | quote }}
  RPC_PORT: {{ .Values.corda.conf.rpc.port | quote }}
  CORS_ALLOWED_ORIGINS: {{ .Values.webServer.conf.corsAllowedOrigins | quote }}
  KEY_STORE_PATH: {{ .Values.webServer.conf.keyStorePath | quote }}
  KEY_STORE_PASSWORD: {{ .Values.webServer.conf.keyStorePassword | quote }}
  KEY_STORE_ALIAS: {{ .Values.webServer.conf.keyStoreAlias | quote }}